#!/usr/bin/python
import os
import random
import sys
import time

run_time = int(os.getenv("RUN_TIME", 5))
exit_code = int(os.getenv("EXIT_CODE", 0))
logdir = os.getenv("LOGDIR", ".")

started_at = time.time()
stop_at = started_at + run_time
n = 0

def step():
    sys.stdout.write("Testing %s\n" % n)
    sys.stdout.flush()
    write_timeseries("rand", n, random.randint(0, 100))

def write_timeseries(name, step, val):
    with open(logdir + "/timeseries-" + name, "a") as f:
        f.write("%i\t%i\t%i\n" % (int(time.time() * 1000), step, val))

while True:
    step()
    if time.time() >= stop_at:
        break
    time.sleep(0.5)
    n = n + 1

sys.exit(exit_code)
