- config: mnist-base
  operations:
    train:
      description: Train the MNIST model
      main: '{{main}} --datadir data --rundir .'
      requires: data
      compare:
        - =epochs
        - =batch-size
        - =lr
        - train#loss step as step
        - train#loss as loss
        - validate#accuracy as accuracy
      objective:
        maximize: validate#accuracy
      flags-import: no
      flags:
        batch-size:
          description: Number of images to include in a training batch
          default: 100
          required: yes
        epochs:
          description: Number of epochs to train
          default: 10
        lr:
          description: Training learning rate
          default: 0.5
    evaluate:
      description: Evaluate a trained model using test data
      main: '{{main}} --test --datadir data --rundir .'
      flags-import: no
      requires:
        - data
        - sources:
            - operation: train
              select: model
      compare:
        - loss step as step
        - loss
        - accuracy
  resources:
    data:
      description: "Yann Lecun's MNIST dataset in compressed IDX format"
      private: yes
      path: data
      sources:
      - url: http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
        sha256: 440fcabf73cc546fa21475e81ea370265605f56be210a4024d2ca8f203523609
      - url: http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
        sha256: 3552534a0a558bbed6aed32b30c495cca23d567ec52cac8be1a0730e8010255c
      - url: http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
        sha256: 8d422c7b0a1c1c79245a5bcf07fe86e33eeafee792b84584aec276f5a2dbc4e6
      - url: http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
        sha256: f7ae60f92e00ec6debd23a6088c31dbd2371eca3ffa0defaefb259924204aec6

- model: mnist-intro
  description: MNIST model from TensorFlow intro tutorial
  extends: mnist-base
  params:
    main: intro

- model: mnist-expert
  description: MNIST model from TensorFlow expert tutorial
  extends: mnist-base
  params:
    main: expert
  operations:
    train:
      flags:
        epochs: 5
        lr: 1e-4
